### ISSUE TITLE
Ödeme Testlerindeki test kullanıcı bilgileri yanlış mı?

### ISSUE THREAD

**Issue by Bytoo** [c1982/GarantiVp#4]
Öncelikle Bu uygulamadaki modellemeler vs. çok işime yaradı teşekkür ederim. normal satış işlemini test ettiğimde kullanıcı şifresi hatalı diye bir mesaj geliyor garanti dökümanlarına baktığımda bilgiler aynı gibi rica etsem kontrol edebilir misin ?

**Comment by Bytoo** [comment]
kullanıcı şifresini "123qweASD/" olarak güncellenmesi lazımmış bilginize.

**Comment by c1982** [comment]
Selamlar,

Doğrulama şansım olmadı fakat commet olarak belirttim verdiğin parolayı.
